[connection]
string = "udp:127.0.0.1:14550"

[camera]
type = "imagezmq"
index = 0
imagezmq_listen_uri = "tcp://127.0.0.1:5555"
rtsp_url = ""

[camera_matrix]
# Focal length
fx = 800.0
fy = 800.0

# Optical center
cx = 500.0
cy = 500.0

[videostreaming]
streamer_type = "imagezmq"
continuous = true
always_detect = true

[platform]
type = "vision_fiducial"

# Visual fiducial platforms array
[vision_fiducial]
[[vision_fiducial.tags]]
id = 1
size = 1.0

[[vision_fiducial.tags]]
id = 2
size = 0.35

[[vision_fiducial.tags]]
id = 3
size = 0.15

[landing]
refresh_rate_seconds = 0.1
max_landing_time_seconds = 60.0
height_threshold = 0.1

[yaw_correction]
enabled = true
speed = 10